name: Report a Bug
description: Please report bugs here. To expedite issue processing, please search open and closed issues before submitting a new one.
title: "Bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Required Fields
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: reproductionSteps
    attributes:
      label: Steps to Reproduce
      description: Provide step by step instructions on how we can reproduce your bug.
      placeholder: | 
        1. Use x argument / navigate to...
        2. Fill this information in...
        3. Go to...
        ...
        n. See error...
    validations:
      required: true
  - type: textarea
    id: expectedBehavior
    attributes:
      label: Expected Behavior
      description: Plese provide a clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
        ## Optional Fields
        
        These fields below are not required to file a bug report; but can be helpful.
  - type: checkboxes
    id: isRegression
    attributes:
      label: Is this a regression?
      description: "Was the desired behavior working before, but has recently changed; or is this a novel issue?"
      options:
        - label: "Yes"
  - type: textarea
    id: associatedIds
    attributes:
      label: Associated Ids
      description: Are there any request ids, session ids, trace ids, commit hashes, etc. that we can use to associate logs or other helpful information with your bug?
  - type: textarea
    id: additionalContext
    attributes: 
      label: Additional Context
      description: You can use this optional field to provide any additional context you think is helpful. This can be any additional information, screenshots, logs, links, etc.
